//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.SinhVienService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinhVienBDO", Namespace="http://schemas.datacontract.org/2004/07/QuanLySinhVienWCF.QuanLySinhVienBDO")]
    [System.SerializableAttribute()]
    public partial class SinhVienBDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HocBongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiSinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoSV {
            get {
                return this.HoSVField;
            }
            set {
                if ((object.ReferenceEquals(this.HoSVField, value) != true)) {
                    this.HoSVField = value;
                    this.RaisePropertyChanged("HoSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HocBong {
            get {
                return this.HocBongField;
            }
            set {
                if ((this.HocBongField.Equals(value) != true)) {
                    this.HocBongField = value;
                    this.RaisePropertyChanged("HocBong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKhoa {
            get {
                return this.MaKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhoaField, value) != true)) {
                    this.MaKhoaField = value;
                    this.RaisePropertyChanged("MaKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSV {
            get {
                return this.MaSVField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSVField, value) != true)) {
                    this.MaSVField = value;
                    this.RaisePropertyChanged("MaSV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiSinh {
            get {
                return this.NoiSinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiSinhField, value) != true)) {
                    this.NoiSinhField = value;
                    this.RaisePropertyChanged("NoiSinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSV {
            get {
                return this.TenSVField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSVField, value) != true)) {
                    this.TenSVField = value;
                    this.RaisePropertyChanged("TenSV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SinhVienService.ISinhVienService")]
    public interface ISinhVienService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Add", ReplyAction="http://tempuri.org/ISinhVienService/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISinhVienService/AddExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Add(QLHS.SinhVienService.SinhVienBDO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Add", ReplyAction="http://tempuri.org/ISinhVienService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(QLHS.SinhVienService.SinhVienBDO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Update", ReplyAction="http://tempuri.org/ISinhVienService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISinhVienService/UpdateExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Update(QLHS.SinhVienService.SinhVienBDO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Update", ReplyAction="http://tempuri.org/ISinhVienService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(QLHS.SinhVienService.SinhVienBDO sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Delete", ReplyAction="http://tempuri.org/ISinhVienService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISinhVienService/DeleteExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Delete(string masv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/Delete", ReplyAction="http://tempuri.org/ISinhVienService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string masv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/GetSinhVien", ReplyAction="http://tempuri.org/ISinhVienService/GetSinhVienResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISinhVienService/GetSinhVienExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        QLHS.SinhVienService.SinhVienBDO GetSinhVien(string Ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/GetSinhVien", ReplyAction="http://tempuri.org/ISinhVienService/GetSinhVienResponse")]
        System.Threading.Tasks.Task<QLHS.SinhVienService.SinhVienBDO> GetSinhVienAsync(string Ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/GetAllSinhVien", ReplyAction="http://tempuri.org/ISinhVienService/GetAllSinhVienResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISinhVienService/GetAllSinhVienExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        QLHS.SinhVienService.SinhVienBDO[] GetAllSinhVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVienService/GetAllSinhVien", ReplyAction="http://tempuri.org/ISinhVienService/GetAllSinhVienResponse")]
        System.Threading.Tasks.Task<QLHS.SinhVienService.SinhVienBDO[]> GetAllSinhVienAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISinhVienServiceChannel : QLHS.SinhVienService.ISinhVienService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SinhVienServiceClient : System.ServiceModel.ClientBase<QLHS.SinhVienService.ISinhVienService>, QLHS.SinhVienService.ISinhVienService {
        
        public SinhVienServiceClient() {
        }
        
        public SinhVienServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SinhVienServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinhVienServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinhVienServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(QLHS.SinhVienService.SinhVienBDO sv) {
            return base.Channel.Add(sv);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(QLHS.SinhVienService.SinhVienBDO sv) {
            return base.Channel.AddAsync(sv);
        }
        
        public bool Update(QLHS.SinhVienService.SinhVienBDO sv) {
            return base.Channel.Update(sv);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(QLHS.SinhVienService.SinhVienBDO sv) {
            return base.Channel.UpdateAsync(sv);
        }
        
        public bool Delete(string masv) {
            return base.Channel.Delete(masv);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string masv) {
            return base.Channel.DeleteAsync(masv);
        }
        
        public QLHS.SinhVienService.SinhVienBDO GetSinhVien(string Ma) {
            return base.Channel.GetSinhVien(Ma);
        }
        
        public System.Threading.Tasks.Task<QLHS.SinhVienService.SinhVienBDO> GetSinhVienAsync(string Ma) {
            return base.Channel.GetSinhVienAsync(Ma);
        }
        
        public QLHS.SinhVienService.SinhVienBDO[] GetAllSinhVien() {
            return base.Channel.GetAllSinhVien();
        }
        
        public System.Threading.Tasks.Task<QLHS.SinhVienService.SinhVienBDO[]> GetAllSinhVienAsync() {
            return base.Channel.GetAllSinhVienAsync();
        }
    }
}
