//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.KetQuaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KetQuaBDO", Namespace="http://schemas.datacontract.org/2004/07/QuanLySinhVienWCF.QuanLySinhVienBDO")]
    [System.SerializableAttribute()]
    public partial class KetQuaBDO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Diem {
            get {
                return this.DiemField;
            }
            set {
                if ((this.DiemField.Equals(value) != true)) {
                    this.DiemField = value;
                    this.RaisePropertyChanged("Diem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaMH {
            get {
                return this.MaMHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMHField, value) != true)) {
                    this.MaMHField = value;
                    this.RaisePropertyChanged("MaMH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaSV {
            get {
                return this.MaSVField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSVField, value) != true)) {
                    this.MaSVField = value;
                    this.RaisePropertyChanged("MaSV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KetQuaService.IKetQuaService")]
    public interface IKetQuaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Add", ReplyAction="http://tempuri.org/IKetQuaService/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IKetQuaService/AddExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Add(QLHS.KetQuaService.KetQuaBDO khoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Add", ReplyAction="http://tempuri.org/IKetQuaService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(QLHS.KetQuaService.KetQuaBDO khoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Update", ReplyAction="http://tempuri.org/IKetQuaService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IKetQuaService/UpdateExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Update(QLHS.KetQuaService.KetQuaBDO khoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Update", ReplyAction="http://tempuri.org/IKetQuaService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(QLHS.KetQuaService.KetQuaBDO khoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Delete", ReplyAction="http://tempuri.org/IKetQuaService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IKetQuaService/DeleteExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Delete(string masv, string mamh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/Delete", ReplyAction="http://tempuri.org/IKetQuaService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string masv, string mamh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/GetKetQua", ReplyAction="http://tempuri.org/IKetQuaService/GetKetQuaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IKetQuaService/GetKetQuaExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        QLHS.KetQuaService.KetQuaBDO GetKetQua(string masv, string mamh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/GetKetQua", ReplyAction="http://tempuri.org/IKetQuaService/GetKetQuaResponse")]
        System.Threading.Tasks.Task<QLHS.KetQuaService.KetQuaBDO> GetKetQuaAsync(string masv, string mamh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/GetAllKetQua", ReplyAction="http://tempuri.org/IKetQuaService/GetAllKetQuaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IKetQuaService/GetAllKetQuaExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        QLHS.KetQuaService.KetQuaBDO[] GetAllKetQua();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKetQuaService/GetAllKetQua", ReplyAction="http://tempuri.org/IKetQuaService/GetAllKetQuaResponse")]
        System.Threading.Tasks.Task<QLHS.KetQuaService.KetQuaBDO[]> GetAllKetQuaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKetQuaServiceChannel : QLHS.KetQuaService.IKetQuaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KetQuaServiceClient : System.ServiceModel.ClientBase<QLHS.KetQuaService.IKetQuaService>, QLHS.KetQuaService.IKetQuaService {
        
        public KetQuaServiceClient() {
        }
        
        public KetQuaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KetQuaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KetQuaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KetQuaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(QLHS.KetQuaService.KetQuaBDO khoa) {
            return base.Channel.Add(khoa);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(QLHS.KetQuaService.KetQuaBDO khoa) {
            return base.Channel.AddAsync(khoa);
        }
        
        public bool Update(QLHS.KetQuaService.KetQuaBDO khoa) {
            return base.Channel.Update(khoa);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(QLHS.KetQuaService.KetQuaBDO khoa) {
            return base.Channel.UpdateAsync(khoa);
        }
        
        public bool Delete(string masv, string mamh) {
            return base.Channel.Delete(masv, mamh);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string masv, string mamh) {
            return base.Channel.DeleteAsync(masv, mamh);
        }
        
        public QLHS.KetQuaService.KetQuaBDO GetKetQua(string masv, string mamh) {
            return base.Channel.GetKetQua(masv, mamh);
        }
        
        public System.Threading.Tasks.Task<QLHS.KetQuaService.KetQuaBDO> GetKetQuaAsync(string masv, string mamh) {
            return base.Channel.GetKetQuaAsync(masv, mamh);
        }
        
        public QLHS.KetQuaService.KetQuaBDO[] GetAllKetQua() {
            return base.Channel.GetAllKetQua();
        }
        
        public System.Threading.Tasks.Task<QLHS.KetQuaService.KetQuaBDO[]> GetAllKetQuaAsync() {
            return base.Channel.GetAllKetQuaAsync();
        }
    }
}
