//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QuanLySinhVienWCF
{
    namespace QuanLySinhVienDAL
    {
        using System;
        using System.Collections.Generic;

        public partial class KetQua
        {
            public string masv { get; set; }
            public string Mamh { get; set; }
            public Nullable<float> Diem { get; set; }

            public virtual MonHoc MonHoc { get; set; }
            public virtual Sinhvien Sinhvien { get; set; }
        }
    }
}
