//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QuanLySinhVienWCF
{
    namespace QuanLySinhVienDAL
    {
        using System;
        using System.Collections.Generic;

        public partial class MonHoc
        {
            public MonHoc()
            {
                this.KetQuas = new HashSet<KetQua>();
            }

            public string Mamh { get; set; }
            public string Tenmh { get; set; }
            public Nullable<int> sotiet { get; set; }

            public virtual ICollection<KetQua> KetQuas { get; set; }
        }
    }
}
